"""add_project_comments

Revision ID: 1a9d20f49a34
Revises: ed6318480d87
Create Date: 2026-05-05 10:27:08.476504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9d20f49a34'
down_revision: Union[str, None] = 'ed6318480d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comments_project_id'), 'project_comments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_comments_user_id'), 'project_comments', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'project_technologies', ['project_id', 'technology_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_technologies', type_='unique')
    op.drop_index(op.f('ix_project_comments_user_id'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_project_id'), table_name='project_comments')
    op.drop_table('project_comments')
    # ### end Alembic commands ###
